### ISSUE TITLE
Ambiguous semantic of updates

### ISSUE THREAD

**Issue by qwiglydee** [qwiglydee/otree-webcomponents#1]
Current scheme: 
- a game maintains state in form of object like `{ obj: { foo: "f", bar: "b" } }`
- a game receives updates that might be partial (i.e. a feedback is given for player's response, or a remote player's move changes value of a single cell nested somewhere)
- the page should redraw all directives that reference affected vars referenced as `obj.foo` or `obj.bar`

An update of form `{ obj: { foo: "foo" } }` might mean:
- whole object `obj` is updated (i.e. new trial/puzzle/game) -- that should affect `obj.foo` and `obj.bar`
- only field `foo` inside `obj` is updated (i.e. the `foo` is a trial feedback or remote player's move) -- that should affect `obj.foo` but not `obj.bar`

**Comment by qwiglydee** [comment]
A possible solution:
- always interpret changes as partial updates
- use explicit `reset` event to reset everything for a new trial/puzzle/round
- use explicit `{ obj: null }` to reset specific nested object

**Comment by oTree-org** [comment]
Some raw thoughts (have not looked at code):

Would be nice if we could structure things so that there is no ambiguity, and that it's obvious to the user without needing to re-check the docs. I also prefer to have very simple semantics.

If the method is called `update`, then users could guess that it is similar to Python `dict.update`.

Would a user ever want to remove attributes from an object? That seems like a rather rare thing, so maybe not an ideal default.

**Comment by qwiglydee** [comment]
@oTree-org the `dict.update` and `Object.assign` work only by top-level keys.

In the simple games made so far, we only have such top-level keys hard-coded in both back and front ends: `{ trial, response, feedback, progress }`. Although in sliders, ther're multiple response/feedbacks for each slider.

More complicated games like puzzles (including the sliders task) will have another set of fields and more important - partial updates.
The logic of such games could be customized via JavaScript, but the underlying view directives should be enough universal to support everything.

**Comment by qwiglydee** [comment]
Another solution:

Make all updates explicit in form { var, val }, like `{ var: 'obj.foo.bar', val: "something" }`, or `{ var: 'obj.foo', val: { nested object } }`.

A game logic layer can decide whether it is full or partial update, and be customized for specific scenarios.
But at least directive layer could have universal unambiguous state updates.

**Comment by qwiglydee** [comment]
And another solution: 

Using one-level dict, with keys in form 'obj.foo', like `{ 'obj.foo.bar': value,  'obj.baz': { ... } }`.
This way it's explicit whether a single field or whole subobject is reset, and allows to update multiple fields at once (i.e. response, feedback, error).

**Comment by qwiglydee** [comment]
implemented the last solution.
